<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<OutputType>Exe</OutputType>
		<RootNamespace>MauiApp1</RootNamespace>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<ApplicationTitle>MauiApp1</ApplicationTitle>
		<ApplicationId>com.companyname.mauiapp1</ApplicationId>
		<ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
		<ApplicationVersion>1</ApplicationVersion>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
		<PackageReference Include="sqlite-net-pcl" Version="1.9.172" />
	</ItemGroup>

</Project>
